CREATE TABLE "genre"
(
    "id"   integer generated by default as identity PRIMARY KEY,
    "name" varchar(64) UNIQUE NOT NULL
);

CREATE TABLE "mpa_rating"
(
    "id"   integer generated by default as identity PRIMARY KEY,
    "name" varchar(5) UNIQUE NOT NULL
);

CREATE TABLE "film"
(
    "id"            integer generated by default as identity PRIMARY KEY,
    "name"          varchar(255) NOT NULL,
    "description"   varchar(500),
    "release_date"  date,
    "duration"      integer,
    "genre_id"      integer,
    "mpa_rating_id" integer
);

CREATE TABLE "user"
(
    "id"       integer generated by default as identity PRIMARY KEY,
    "email"    varchar(64) UNIQUE,
    "login"    varchar(64) UNIQUE,
    "name"     varchar(64),
    "birthday" timestamp
);

CREATE TABLE "friend"
(
    "follower_id" integer,
    "followed_id" integer,
    "status"      bool,
    PRIMARY KEY ("follower_id", "followed_id")
);

ALTER TABLE "film"
    ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("id");

ALTER TABLE "film"
    ADD FOREIGN KEY ("mpa_rating_id") REFERENCES "mpa_rating" ("id");

ALTER TABLE "friend"
    ADD FOREIGN KEY ("follower_id") REFERENCES "user" ("id");

ALTER TABLE "friend"
    ADD FOREIGN KEY ("followed_id") REFERENCES "user" ("id");
